### ISSUE TITLE
Not found on NPM

### ISSUE THREAD

**Issue by paulwib** [floatdrop/pinkie-promise#4]
Seems to have gone 404, also see https://github.com/floatdrop/pinkie/issues/16.

**Comment by BlackHole1** [comment]
Temporary solution:
`npm install --save pinkie-promise@2.0.2`

**Comment by thangngoc89** [comment]
It's back online.

**Comment by jmeridth** [comment]
Kind of but not really :cry: 
![screenshot from 2018-01-06 11-00-03](https://user-images.githubusercontent.com/35014/34642960-d1be1058-f2d0-11e7-8fb4-04ec2c5106db.png)

**Comment by thangngoc89** [comment]
Yarn install works again for me.

**Comment by gniquil** [comment]
And can't use your temporary solution as i don't even know which lib is actually using this lib

**Comment by jarretmoses** [comment]
This does not seem to appear on the Yarn registry as of now. @thangngoc89 you can install this through yarn?

**Comment by thangngoc89** [comment]
@gniquil I don't know about npm, but yarn will produce and log file and you can trace it in there

webpack-dev-server -> yargs@6.0.6 -> find-up -> pkg-up -> pinkie-promise

**Comment by BlackHole1** [comment]
@gniquil You can look at the log file. Find out the invoked package. It seems that NPM is backing up?

**Comment by thangngoc89** [comment]
yarn is down again :(

**Comment by chrisbutler** [comment]
still not working on npm for me

**Comment by gniquil** [comment]
@thangngoc89 haha ok yeah, webpacker for rails for me.

So does that mean all Rails with webpacker deployment is now broken?

**Comment by BlackHole1** [comment]
other package also have problems

**Comment by thangngoc89** [comment]
@gniquil pretty much everyone who's working on frontend projects these days will be affected

**Comment by BlackHole1** [comment]
@thangngoc89 What's the matter?

**Comment by thangngoc89** [comment]
@BlackHole1 it's a dependency of dependency of webpack-dev-server

**Comment by thangngoc89** [comment]
@floatdrop could you please republish the old versions? 

Here is the list:

1.0.0
2.0.0
2.0.1
2.0.2

**Comment by thangngoc89** [comment]
For anyone who's reading this thread, @floatdrop has unpublished all of his packages (sounds like leftpad to me). Random people is taking the package so please do not install the code. !!!

**Comment by squigg** [comment]
It's gone again:
![image](https://user-images.githubusercontent.com/4279310/34643122-cbe05aa6-f316-11e7-8312-86659c94a860.png)

**Comment by paulwib** [comment]
@squigg please don't ask people to claim this package until we hear from @floatdrop.

**Comment by thangngoc89** [comment]
@paulwib it have already been claimed

**Comment by mbensch** [comment]
@floatdrop's NPM account was deleted and all his packages. I have re-published a few but it's way too much. I can't republish older versions but I can probably publish a new 1.0.X Not really sure what to do from here because it's breaking a lot of stuff right now.

**Comment by squigg** [comment]
@paulwib it was already re-claimed and re-published, and then went again, hence my comment. Considering npm itself pretty much asks you to claim it when you browse (that's a screenshot of the npm website btw!), I didn't think I was pointing out anything over and above the obvious.

**Comment by Oduig** [comment]
Leftpad 2.0. This package is now breaking all Ionic builds:

https://stackoverflow.com/questions/48131111/ionic-pro-build-failed-npm-err-404-not-found-pinkie-promise/48131180#48131180

What does it mean for someone to re-claim the package? Could they push malicious code to have everyone pull it in, or is that not a risk?

**Comment by squigg** [comment]
Yes I think this is possible. See mbensch post above, as he already did this.

**Comment by paulwib** [comment]
@squigg fair enough, it's difficult to know what to do in these situations. People want to help by republishing packages, but of course someone malicious could republish a new patch version with malicious code and people without lock files could unintentionally pull it into their build.

**Comment by anveo** [comment]
Keep an eye on https://github.com/npm/registry/issues/255

**Comment by Amurmurmur** [comment]
@mbensch They ask not to republish packages:
https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by kbrandwijk** [comment]
@Amurmurmur they ask **_NOT_** to republish

**Comment by Amurmurmur** [comment]
@kbrandwijk Mistypo :/

**Comment by quentinyang** [comment]
waiting for recovery

**Comment by jcreamer898** [comment]
I'm having flashbacks to leftpad...

**Comment by sualex** [comment]
+1. The work has stopped for me ( . Meteor project.

**Comment by sixertoy** [comment]
```bash
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
error Received malformed response from registry for "pinkie-promise". The registry may be down.
```

:'(

**Comment by Taylor123** [comment]
Still seeing 404 on npm

**Comment by staycreativedesign** [comment]
So I just did a 
```
npm install ionic cordova -g
```

and its not finding pinkie-promise and im assuming its because he pulled it?? What are the next steps?

**Comment by shacal** [comment]
This is one of the biggest reason, I hate people to use packages "IsString" etc that do stupid one-liners and then are used everywhere.
Code more, less packet whoring...

**Comment by Amurmurmur** [comment]
Guys for everyone who is waiting on pinkie-promise
https://gist.github.com/Amurmurmur/860691b93e391a86facede780656f8ab

**Comment by Kaptard** [comment]
[NPM Status Page](https://status.npmjs.org/) 
(they're aware of it and should be fixed soon)

**Comment by mikicho** [comment]
Still 404 for me..

**Comment by ghost** [comment]
npm/registry/issues/255

**Comment by brunocroh** [comment]
Npm's answer
https://twitter.com/npmstatus/status/949735322522345472

**Comment by liquidmetal** [comment]
This is being tracked here: https://github.com/npm/registry/issues/255

**Comment by anedisi** [comment]
it looks like its restored again, it works for me

**Comment by shacal** [comment]
Sysadmins replacing Intel machines with Raspberry PI's :D

**Comment by krupper** [comment]
it's solved :D

**Comment by risinek** [comment]
party's over, back to work

**Comment by danielweck** [comment]
Beware though, because `pinkie` was re-published by another dev!
https://github.com/floatdrop/pinkie/issues/18#issuecomment-355780834

**Comment by danielweck** [comment]
You may track the `pinkie` issue at NPM's "registry" repository: https://github.com/npm/registry/issues/256

**Comment by danielweck** [comment]
Update:
https://github.com/npm/registry/issues/256#issuecomment-355785321
Probably a good idea to clear npm / yarn cache, node_modules, and lock files...

**Comment by czuendorf** [comment]
Rethink the usage of this package, and the necessity of an additional dependency.
I know it may be easier to type "npm install" than to think about a solution. But today you all discovered the disadvantages. Only create dependencies when they are needed (and for good reasons) and not because ONE line of code. Even copy-paste would be faster than 'npm install' and 'require("pinkie-promise")':
https://github.com/floatdrop/pinkie-promise/blob/master/index.js#L3

Imagine what happens if someone creates a module, waits until it is used quite often, and then deletes it because of bad intentions.

Require modules which you can rely on, and which are maintained but not only one person.

**Comment by floatdrop** [comment]
> party's over, back to work

Missed whole party. Oh gosh.
