### ISSUE TITLE
Not Found: pinkie-promise@https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.0.tgz

### ISSUE THREAD

**Issue by rongduan-zhu** [floatdrop/pinkie-promise#6]
Hi @floatdrop, one of our packages have a dependency on pinkie-promise-2.0.0 but it looks like it is not in the npm registry.

```
npm ERR! code E404
npm ERR! 404 Not Found: pinkie-promise@https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.0.tgz
```

Can you please publish 2.0.0 to the npm registry?

**Comment by jpatadia** [comment]
Facing the same issue @floatdrop . Do we know if this will be resolved soon?

**Comment by bromanv** [comment]
I have de same issue, and https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.0.tgz  return {"error":"package could not be found."} @floatdrop  is there other repository or way to install it

**Comment by kristrt** [comment]
I am facing same issue,  https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.0.tgz return {"error":"package could not be found."} and it is intermittent.  @floatdrop   Could you suggest what is the stable version for pinkie-promise package.

**Comment by floatdrop** [comment]
https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.0.tgz works well for me - check, that you do not have caching proxy in between registry and npm command.

**Comment by rongduan-zhu** [comment]
@floatdrop cool, it is working now and thank you for checking. I guess @kristrt is right that this is probably an intermittent issue.
